sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

sky.alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5t8dAdTWeoaLfit1EZ5m
  access-key-secret: f1RJ2PoNs2E2sFYMayqBBeqT0RCV9X
  bucket-name: n1ce-sky-take-out